/* -*- tab-width: 2 -*- */
'use strict';

// Don't rely on this file. I'll have to split it one day.

const misc = {
  artistPalette: '🎨',
  axe: '🪓',
  bamumLetterPhaseDYen: '𖤍',
  bamumLetterPhaseENgkaami: '𖦹',
  bomb: '💣',
  bookmark: '🔖',
  briefcase: '💼',
  broom: '🧹',
  cancellationX: '🗙',
  carpentrySaw: '🪚',
  chains: '⛓',
  chair: '🪑',
  chequeredFlag: '🏁',
  clipboard: '📋',
  cookie: '🍪',
  crossMark: '❌',
  crystalBall: '🔮',
  electricLightBulb: '💡',
  eyes: '👀',
  fire: '🔥',
  fish: '🐟',
  floppyDisk: '💾',
  gear: '⚙',
  globeWithMeridians: '🌐',
  hammerAndWrench: '🛠',
  hourglassWithFlowingSand: '⏳',
  hundredPointsSymbol: '💯',
  javaneseLeftRerenggan: '꧁',
  javaneseRightRerenggan: '꧂',
  keyboard: '⌨',
  label: '🏷',
  leftPointingMagnifyingGlass: '🔍',
  link: '🔗',
  lock: '🔒',
  memo: '📝',
  microscope: '🔬',
  multipleMusicalNotes: '🎶',
  nameBadge: '📛',
  noEntry: '⛔',
  noEntrySign: '🚫',
  northEastArrow: '↗',
  octagonalSign: '🛑',
  openLock: '🔓',
  paperclip: '📎',
  partyPopper: '🎉',
  policeOfficer: '👮',
  pushpin: '📌',
  railwayTrack: '🛤',
  rainbow: '🌈',
  rocket: '🚀',
  satelliteDish: '📡',
  scales: '⚖',
  scroll: '📜',
  shield: '🛡',
  shootingStar: '🌠',
  shrug: '🤷',
  slotMachine: '🎰',
  sparkles: '✨',
  stethoscope: '🩺',
  telephoneReceiver: '📞',
  telescope: '🔭',
  thumbsDownSign: '👎',
  thumbsUpSign: '👍',
  topHat: '🎩',
  trophy: '🏆',
  warningSign: '⚠',
  wastebasket: '🗑',
  whiteHeavyCheckMark: '✅',
  wood: '🪵',
};


module.exports = misc;
